// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromptOps.Infrastructure.Persistence;

#nullable disable

namespace PromptOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PromptOpsDbContext))]
    partial class PromptOpsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PromptOps.Infrastructure.Persistence.Records.PromptDependencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PromptVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetPromptVersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PromptVersionId");

                    b.ToTable("PromptDependencies", (string)null);
                });

            modelBuilder.Entity("PromptOps.Infrastructure.Persistence.Records.PromptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prompts", (string)null);
                });

            modelBuilder.Entity("PromptOps.Infrastructure.Persistence.Records.PromptVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangelogEntry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PromptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateVariables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PromptId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("PromptVersions", (string)null);
                });

            modelBuilder.Entity("PromptOps.Infrastructure.Persistence.Records.PromptDependencyRecord", b =>
                {
                    b.HasOne("PromptOps.Infrastructure.Persistence.Records.PromptVersionRecord", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("PromptVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PromptOps.Infrastructure.Persistence.Records.PromptRecord", b =>
                {
                    b.OwnsOne("PromptOps.Infrastructure.Persistence.Records.PromptMetadataRecord", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("PromptId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Categories")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ExternalRefs")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Owners")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tags")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PromptId");

                            b1.ToTable("PromptMetadata", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PromptId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("PromptOps.Infrastructure.Persistence.Records.PromptVersionRecord", b =>
                {
                    b.HasOne("PromptOps.Infrastructure.Persistence.Records.PromptRecord", null)
                        .WithMany("Versions")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PromptOps.Infrastructure.Persistence.Records.PromptRecord", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("PromptOps.Infrastructure.Persistence.Records.PromptVersionRecord", b =>
                {
                    b.Navigation("Dependencies");
                });
#pragma warning restore 612, 618
        }
    }
}
